FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir jupyter nbconvert

COPY . .

WORKDIR /app/dataLayer/silver

CMD ["jupyter", "nbconvert", "--to", "notebook", "--execute", "analysis_silver.ipynb", "--output", "analysis_silver_executado.ipynb"]
