FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir jupyter nbconvert

COPY . .

WORKDIR /app/dataLayer/raw

CMD ["jupyter", "nbconvert", "--to", "notebook", "--execute", "analytics.ipynb", "--output", "analytics.ipynb"]
