FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir jupyter nbconvert

COPY . .

WORKDIR /app/transformer

CMD ["jupyter", "nbconvert", "--to", "notebook", "--execute", "etl_silver_to_gold.ipynb", "--output", "etl_silver_to_gold.ipynb"]
